### ISSUE TITLE
(Android) MaterialShapeManager.InitializeClipPath() - ObjectDisposedException

### ISSUE THREAD

**Issue by sasa-bobic** [ChasakisD/Xamarin.Forms.BackgroundKit#58] opened 2020-01-23 09:05 UTC
Hi @ChasakisD, 

I'm using MaterialContentView inside CollectionView (XF 4.4) and I'm getting a random ObjectDisposedExpection while scrolling through the list. 

Exception points to this method (MaterialShapeManager, line 122); it seems that "_clipPath" is sometimes disposed:

>         private void InitializeClipPath(int width, int height)
>         {
>             if (width <= 0 || height <= 0) return;
> 
>             var canvasBounds = new RectF(0, 0, width, height);
>             canvasBounds.Inset(-1, -1);
> 
>             /* Always prefer border path. If there is no need, the provider will return the default one */
>             var clipPath = PathProvider.CreateBorderedPath(width, height);
> 
>             _clipPath.Reset();
>             _clipPath.Set(clipPath);
> 
>             _maskPath.Reset();
>             _maskPath.AddRect(canvasBounds, Path.Direction.Cw);
>             _maskPath.InvokeOp(_clipPath, Path.Op.Difference);
>         }

**StackTrace:**

> at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <af1c6fdcff1a4da4a0e44a8cdef352da>:0 
> at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <af1c6fdcff1a4da4a0e44a8cdef352da>:0 
> at Android.Graphics.Path.Reset () [0x0000a] in <d706cf8faf5542949900cf6d57864528>:0 
> at XamarinBackgroundKit.Android.Renderers.MaterialShapeManager.InitializeClipPath (System.Int32 width, System.Int32 height) [0x0003b] in /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialShapeManager.cs:122 
> at XamarinBackgroundKit.Android.Renderers.MaterialShapeManager.Draw (Android.Views.View view, Android.Graphics.Canvas canvas, System.Action dispatchDraw) [0x00009] in /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialShapeManager.cs:99 
> at XamarinBackgroundKit.Android.Renderers.MaterialBackgroundManager.Draw (Android.Views.View view, Android.Graphics.Canvas canvas, System.Action dispatchDraw) [0x00000] in /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialBackgroundManager.cs:402 
> at XamarinBackgroundKit.Android.Renderers.MaterialContentViewRenderer.DispatchDraw (Android.Graphics.Canvas canvas) [0x00014] in /Users/chasakisd/Desktop/GitRepos/Xamarin.Forms.BackgroundKit-new/src/XamarinBackgroundKit.Android/Renderers/MaterialContentViewRenderer.cs:53 
> at Android.Views.View.n_DispatchDraw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x00011] in <d706cf8faf5542949900cf6d57864528>:0 
> at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.77(intptr,intptr,intptr)

**Comment by ChasakisD** [comment] 2020-01-24 15:20
@sasa-bobic I published version 2.0.1 to nuget. It will be available soon. Please try this version and tell me if the crash happens again.

**Comment by ChasakisD** [comment] 2020-01-27 12:22
In Version 2.0.2 should be fixed. Try update to version 2.0.2 and check if the error still happens. If yes, send me a reproduction project.

**Comment by ChasakisD** [comment] 2020-03-28 16:24
Closed due to not responding. If the issue is still occurring please reopen it

**Closed as completed by ChasakisD** 2020-03-28 16:24 UTC
